platform :ios, '9.0'

target 'react-native-starter' do

  pod 'Firebase/Core', '~> 5.15.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  # pod 'Firebase/Invites', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Performance', '~> 5.15.0'
  
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'DevSupport',
  ]
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
